### ISSUE TITLE
No Cherry MX dimensions

### ISSUE THREAD

**Issue by LinirZamir** [dankwookiee/Kieeboard#3]
Hi, I am trying to create the keycaps as the instructed, but I can't find the Cherry keycaps dimensions. 
The width and length are the same as the OEM, as mentioned, but the height and front / rear angle are different.

**Comment by dankwookiee** [comment]
@Morters thanks for the note. I've uploaded the spec sheet that I found for Cherry MX caps and switches. Hope this helps, sorry for any wait on your part. Haven't looked at this in a long time. 

https://github.com/dankwookiee/Kieeboard/blob/master/Cherry%20Specifications%20Sheet.pdf
